### ISSUE TITLE
`expires` config is not taking in account

### ISSUE THREAD

**Issue by gido** [antistatique/leckerli#8]
The expired set in the json config is not taking in account:

```
{
   "expires": 90
}
```

this code set always the value to one month:
https://github.com/antistatique/leckerli/blob/2d13e0885ccced7682fef49b9fab3b3a1b13f2f1/src/hooks/useSettings.ts#L31

**Comment by Yago** [comment]
Yes it [is](https://github.com/antistatique/leckerli/blob/2d13e0885ccced7682fef49b9fab3b3a1b13f2f1/src/hooks/useSettings.ts#L41). Is there a bug?
